### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by markusschmitz53** [hukkelas/deep_privacy2#10]
I ran into a problem trying to install deep_privacy2 on Windows. Seems like detectron can't be installed on Windows without changes to the package: https://github.com/facebookresearch/detectron2/issues/1601
Windows is not officially supported by detectron.

Maybe a hint regarding supported OS in the guide https://www.hukkelas.no/deep_privacy2/#/README would be helpful to other users?

**Comment by slslazy** [comment]
I had the same issue. Not a great solution but it works in WSL.

**Comment by hukkelas** [comment]
I've added a hint in the readme with [this commit](https://github.com/hukkelas/deep_privacy2/commit/f2756dfb679e40aafbb85c0243ec1dfdc8d81cc4).

The DeepPrivacy2 code should work fine with windows if you're able to install detectron2.

**Comment by hukkelas** [comment]
Closing this issue for now
