### ISSUE TITLE
ModuleNotFoundError: No module named 'tops'

### ISSUE THREAD

**Issue by PaulSudarshan** [hukkelas/deep_privacy2#11]
Getting the following error while executing the anonymize.py script.

Traceback (most recent call last):
  File "/content/deep_privacy2/anonymize.py", line 2, in <module>
    import tops
ModuleNotFoundError: No module named 'tops'

I have already browsed through the repository, but couldn't find any module called tops.

**Comment by PedroKBrant** [comment]
You can try this 
`pip install git+https://github.com/hukkelas/torch_ops.git`

**Comment by PaulSudarshan** [comment]
ModuleNotFoundError: No module named 'densepose'

from .cse import from_E_to_vertex
  File "/content/deep_privacy2/dp2/utils/cse.py", line 3, in <module>
    from densepose.modeling.cse.utils import get_closest_vertices_mask_from_ES

there seems to be a missing module @PedroKBrant

**Comment by petale-azerty** [comment]
> ModuleNotFoundError: No module named 'densepose'
> 
> from .cse import from_E_to_vertex File "/content/deep_privacy2/dp2/utils/cse.py", line 3, in from densepose.modeling.cse.utils import get_closest_vertices_mask_from_ES
> 
> there seems to be a missing module @PedroKBrant

I have the problem, even if I use the setup.py file to install. 

deep_privacy2-master/dp2/utils/cse.py", line 3, in <module>
    from densepose.modeling.cse.utils import get_closest_vertices_mask_from_ES
ModuleNotFoundError: No module named 'densepose'

Can you please help us ?

**Comment by hukkelas** [comment]
Can you show the output of `pip list` after running `pip install git+https://github.com/hukkelas/torch_ops.git`?

If densepose is in the list, please show the complete command you use to get the error above and report the  complete error message.

**Comment by hukkelas** [comment]
That's strange. Could you try to install densepose alone?

```
pip install git+https://github.com/facebookresearch/detectron2@96c752ce821a3340e27edd51c28a00665dd32a30#subdirectory=projects/DensePose
```

**Comment by petale-azerty** [comment]
Damn, this is the issue. 

First of all : do you think i should install the one who're not installed, manually ? 

Successfully built detectron2-densepose
Installing collected packages: av, detectron2-densepose
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dp2 0.1.0 requires einops, which is not installed.
dp2 0.1.0 requires einops_exts, which is not installed.
dp2 0.1.0 requires fast_pytorch_kmeans, which is not installed.
dp2 0.1.0 requires motpy@ git+https://github.com/wmuron/motpy@c77f85d27e371c0a298e9a88ca99292d9b9cbe6b, which is not installed.
dp2 0.1.0 requires ninja==1.10.2, which is not installed.
dp2 0.1.0 requires pyspng, which is not installed.
dp2 0.1.0 requires regex, which is not installed.
dp2 0.1.0 requires resize_right==0.0.2, which is not installed.
dp2 0.1.0 requires torch_fidelity==0.3.0, which is not installed.
dp2 0.1.0 requires wandb, which is not installed.
dp2 0.1.0 requires imageio==2.4.1, but you have imageio 2.25.0 which is incompatible.
dp2 0.1.0 requires pillow==8.3.1, but you have pillow 9.4.0 which is incompatible.
dp2 0.1.0 requires scipy==1.7.1, but you have scipy 1.10.0 which is incompatible.
dp2 0.1.0 requires setuptools==59.5.0, but you have setuptools 65.6.3 which is incompatible.
Successfully installed av-10.0.0 detectron2-densepose-0.6

Then when i do : 

python3 anonymize.py configs/anonymizers/FB_cse.py --webcam 


Here is the answer : 

ImportError: dlopen(/Users/mmm24/miniconda3/lib/python3.9/site-packages/pycocotools/_mask.cpython-39-darwin.so, 0x0002): tried: '/Users/mmm24/miniconda3/lib/python3.9/site-packages/pycocotools/_mask.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))

**Comment by hukkelas** [comment]
> First of all : do you think i should install the one who're not installed, manually ?

That can help debug your issue at least.

Are you trying to install this on an arm CPU? If so, a mac?

**Comment by petale-azerty** [comment]
> > First of all : do you think i should install the one who're not installed, manually ?
> 
> That can help debug your issue at least.
> 
> Are you trying to install this on an arm CPU? If so, a mac?

Yes I do. Is this the problem ? Because it works with the deepPrivacy (1) that you made

**Comment by petale-azerty** [comment]
Ohhhhhh it finally works. I just had to install few others packages, but now it's okay. 
Thank a lot for your help, 
now let's have some fun ! 
☺︎

**Comment by petale-azerty** [comment]
Ok, I'm sorry, just an other one now : 

- why is the frame so slow with the webcam ? How can we change it ?

**Comment by hukkelas** [comment]
> why is the frame so slow with the webcam ? How can we change it ?

Because the webcam FPS follows the number of frames the anonymization inference uses. On an RTX 3090 I achieve roughly 5-10 FPS for a single person in the image. 

It is possible to wastly improve inference time if you optimize the current code further, but this is something I currently do not have time to do.

**Comment by hukkelas** [comment]
Closing this issue for now. Reopen if you have further issues.

**Comment by shoutOutYangJie** [comment]
> Ohhhhhh it finally works. I just had to install few others packages, but now it's okay. Thank a lot for your help, now let's have some fun ! ☺︎

I meet a same question,  what packages you install

**Comment by petale-azerty** [comment]
> > Ohhhhhh it finally works. I just had to install few others packages, but now it's okay. Thank a lot for your help, now let's have some fun ! ☺︎
> 
> I meet a same question, what packages you install

Hello you, 

As I remind, I install manually every packages that were missing. 
Every time the answer is : No module name '(exemple)' --> you have yo install in your repo or with pip or with other github link :))

Hope it helps
