### ISSUE TITLE
MPS on MacOS?

### ISSUE THREAD

**Issue by sameastham** [hukkelas/deep_privacy2#12]
Before I start digging through the code, is there a straightforward way to use MPS for M1/M2 Macs rather than CUDA for NVIDIA? PyTorch does support MPS: https://pytorch.org/docs/stable/notes/mps.html

**Comment by hukkelas** [comment]
I have not tested with MPS on MacOS and it is not supported out of the box. The framework assumes CUDA device. 

All CPU-to-CUDA transfers are done with helper function from the extension "tops". To use MPS  instead you should only need to change the following functions:
[`to_cuda`](https://github.com/hukkelas/torch_ops/blob/f37203980a50a93092e8e4a49de1b318c5005ddd/tops/utils/torch_utils.py#L30) and [`get_device`](https://github.com/hukkelas/torch_ops/blob/f37203980a50a93092e8e4a49de1b318c5005ddd/tops/utils/torch_utils.py#L45).


Let me know if you get it to work!

**Comment by hukkelas** [comment]
Closing this issue for now. Reopen if you have further issues.
