### ISSUE TITLE
Is the TRACK function working properly?

### ISSUE THREAD

**Issue by chomichaelyoshi** [hukkelas/deep_privacy2#14]
Thanks for sharing the great code.

By the way, is the track function working correctly?
When using anonymize.py to anonymize a video, it appears that the same person is not anonymized in the same style even if track is specified as an argument.
Specifically, even if I specify track as an argument, all_styles=None, so the tracking results do not seem to be reflected in the style.
I would appreciate it if you could tell me how this should be corrected.

**Comment by hukkelas** [comment]
It should work as expected. Can you report the complete command you use to anonymize the video?

**Comment by chomichaelyoshi** [comment]
Thanks for the reply.
Here are the commands I used.
python3 anonymize.py configs/anonymizers/FB_cse.py -i project.mp4 -o output.mp4 --track

**Comment by chomichaelyoshi** [comment]
I changed the truncation_value, which is 0 by default, to None and it now tracks correctly.
It seems that if the branch at line 138 of deep_privacy2/dp2/generator/base.py is set to 0, it does not branch correctly.
This may be a mistake that occurs only in my environment, but I'll keep a record of it.

**Comment by hukkelas** [comment]
That's great! All my tracking experiments have been with multi modal truncation, so it should work with '--mt' argument as well!

**Comment by chomichaelyoshi** [comment]
I understood that it was because I was not using multi modal truncation.
Thank you for your response.
