### ISSUE TITLE
Weights for the model

### ISSUE THREAD

**Issue by annatelegina** [hukkelas/deep_privacy2#2]
Hi Hakon, 

Thank you for your repo. I found your work very curious to understand how it will work on my own pictures. 
How can I test your algorithm? Are there any weights for your model?

**Comment by hukkelas** [comment]
Hi Anna,

Anonymizing your own images is described [here](https://github.com/hukkelas/deep_privacy2#anonymization). These commands should automatically download pre-trained models for you. 

Please let me know if you in into any issues on your own images!

**Comment by hukkelas** [comment]
Closing this issue for now. Please reopen it if your question was not answered :)

**Comment by shoutOutYangJie** [comment]
weight is Gone
