### ISSUE TITLE
Can't install Deep_privacy2 in the Google Collab with miniconda and python3.9

### ISSUE THREAD

**Issue by AbdirayimovS** [hukkelas/deep_privacy2#21]
Hello all,

I was given to implement deep_privacy2 anonymization in Google Colab. 
After successfully installing miniconda and pytorch, I run the following code:
`pip install git+https://github.com/hukkelas/deep_privacy2/`

## Result
As a n output I got following error:
<img width="1407" alt="image" src="https://github.com/hukkelas/deep_privacy2/assets/96771858/fd0419a6-6974-4fef-9924-21a529122f5a">

Looking forward for you help!

**Comment by PedroKBrant** [comment]
Hello @AbdirayimovS , did you managed tô solve this issue? I'm also interested in training the network on collab

**Comment by hukkelas** [comment]
Hi, I'm not familiar with google colab and do not have time currently to look into it. Although, it should not be required to use miniconda/anaconda on google cloud.

**Comment by Gordon-4389** [comment]
You can clone and build it separately, but you have to loosen the dependencies:
1. First clone the repo `!git clone https://github.com/hukkelas/deep_privacy2/`
2. Then, in 'setup.py' change the following using a script:
- `scipy==1.7.1` to `scipy`
- `setuptools==5.9.5.0` to `setuptools`
- `pillow==8.3.1` to `pillow`
3. Then, I just build:
```
%cd deep_privacy2
! pip install -e .
%cd ..
```
From this, I managed to get anonymization working, but I've run into some of my own issues I am working to resolve.

**Comment by ranaarslankhalid** [comment]
Hello @Gordon-4389 ,

I've cloned the repository but I'm not able to install the package pyspng I'm trying to do it in Anaconda on macOS. Any suggestions how to resolve it ?

**Comment by binodil** [comment]
I have solved the issue with downgrading the python to 3.8 or 3.9. Sorry for late response. @Gordon-4389 solution looks very promising.
