### ISSUE TITLE
Cant open camera by index

### ISSUE THREAD

**Issue by ammar-deep** [hukkelas/deep_privacy2#6]
I have installed it with docker. It works fine on static images. However when I do webcam anonymization, I get "cant open camera by index". 

I have tried built in camera and also usb camera both are giving same error.

I have also tried to change the index here https://github.com/hukkelas/deep_privacy2/blob/50ce66a75ec6e58db714ddfa91e8f2731d87d3b2/anonymize.py#L158 from 0-2 but the problem remains.

When i run a dummy open camera on a separate python file using opencv it works fine.

**Comment by hukkelas** [comment]
Did you test your dummy script inside of the docker container?

**Comment by ammar-deep** [comment]
No I didn't. Do I need to?

**Comment by ammar-deep** [comment]
I tried to run my dummy script inside the docker container and it gives the same above error.
Well what can be the issue in this case?

**Comment by hukkelas** [comment]
Yes, this is an issue with docker then. Check [this stackoverflow](https://stackoverflow.com/questions/62929645/unable-to-open-camera-using-cv2-videocapture0-in-docker-ubuntu-host) post about it, where the same issue is documented.
